apiVersion: v1
kind: Service
metadata:
  labels:
    name: labakes-app
  name: labakes-app-svc
  namespace: labakes
spec:
  type: LoadBalancer
  selector:
    app: labakes-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
